### ISSUE TITLE
no tracks in country

### ISSUE THREAD

**Issue by vanderleisp** [fsahin/artist-explorer#10]
I've been testing the app in different browsers here on my desktop, and even serving it as a file to the browser usually works well, but the idea is to integrate portion of it in a mobile app with other features.
To develop this mobile app I'm planning to use the Titanium cross-platform tool, and it will be based on a webview page, but always that I test the artist-explorer then I get the message "ooops, seems like there are no available tracks in your country".
As the location and GPS are already setup in the manifest (and other apps already make use of same configuration and works well), and on desktop it also checks that I'm located in Brazil and works well, then what could be causing this message to shows up ??

- - maybe something related to the issue #7 so I'll test later if this is the problem.

**Comment by fsahin** [comment]
The app makes a request to https://freegeoip.net/json/ to get current users IP address. Can you add logs to see if that part of the code (below) gets the right country in your mobile app ? 

```javascript
 $.ajax({
            url: "https://freegeoip.net/json/"
        }).done(function (data) {
            userCountry = data.country_code;
        });
```

**Comment by vanderleisp** [comment]
yes, I got to this point already, but still didn't find a solution to get this log done.
Couldn't yet find a way to test this inside the Titanium wrapper, but testing the app on different browsers on my desktop (Opera 28 and Chrome 41) I got always the message    net::ERR_BLOCKED_BY_CLIENT either testing it via server running at address 8080 or trying to run as a file on browser.
So still trying to fix this at browser and then go back to Titanium and fix it there.
One point I just tested was to go to your address, https://artistexplorer.spotify.com/ , and run it, and then also got the same error message on both Opera 28 and Chrome 41, but using the old Opera 12 then the json works well but got an error on line 58 of the main.js file, which is where you go and getArtist.
As Titanium uses the Chrome embedded then seems its why on desktop also the json doesn't work.

Below is the log for the json error on Opera 28 and Chrome 41:

GET https://freegeoip.net/json/ net::ERR_BLOCKED_BY_CLIENT         jquery-1.10.2.min.js:9659 jQuery.ajaxTransport.send                                                                      jquery-1.10.2.min.js:9210
jQuery.extend.ajax                                                                                   main.js:56
(anonymous function)

Below is the low with Opera 12:
Request:
GET /json/ HTTP/1.1
User-Agent: Opera/9.80 (Windows NT 6.1; WOW64) Presto/2.12.388 Version/12.17
Host: freegeoip.net
Accept: text/html, application/xml;q=0.9, application/xhtml+xml, image/png, image/webp, image/jpeg, image/gif, image/x-xbitmap, */*;q=0.1
Accept-Language: en-US,en;q=0.9
Accept-Encoding: gzip, deflate
Connection: Keep-Alive
DNT: 1

Response
HTTP/1.1 200 OK
Server: nginx/1.4.6 (Ubuntu)
Date: Sun, 22 Mar 2015 21:46:19 GMT
Content-Type: application/json
Content-Length: 195
Connection: keep-alive
Access-Control-Allow-Method: GET, HEAD, OPTIONS
Access-Control-Allow-Origin: *
X-Database-Date: Wed, 04 Mar 2015 16:56:17 GMT
Strict-Transport-Security: max-age=15768000

{"ip":"xxx.190.xxx.xx","country_code":"BR","country_name":"Brazil","region_code":"","region_name":"","city":"","zip_code":"","time_zone":"","latitude":-xx.548,"longitude":-xx.636,"metro_code":0}

**Comment by fsahin** [comment]
Since, this is a special case for your app and not a problem for artist-explorer itself, I will close this issue. Seems like you reduced the problem to not being able to call freegeoip inside a Titanium container. You can try to get help on stackoverflow or for now you can disable that request and default to a hardcoded country for development purposes.

**Comment by vanderleisp** [comment]
so just put "BR" there and do all other the tests ??
if I keep the call and only hardcode to Brazil then could run all other features or still there are some other things that depend on country code ?

**Comment by fsahin** [comment]
top-tracks results depend on the country. So, you will always get results for Brasil only. I don't think there are any other features that depend on the country right now.
