### ISSUE TITLE
Error 502 on search

### ISSUE THREAD

**Issue by ebuildy** [fsahin/artist-explorer#15]
Front end calls => https://artistexplorer.spotify.com/spotify/search?FR which gives a 502 Nginx bad gateway error ;-(

**Comment by fsahin** [comment]
@ebuildy Maybe that was a temporary issue. I can't reproduce the problem at the moment. Also that uri doesn't seem to be right. It should be somewhat like **https://artistexplorer.spotify.com/spotify/search?limit=50&market=FR&q=xxx*&type=artist**
